GOPATH = $(shell go env GOPATH)

$(GOPATH)/bin/fabric:
	go install github.com/danielmiessler/fabric@latest

$(GOPATH)/bin/html2markdown:
	go install github.com/JohannesKaufmann/html-to-markdown/v2/cli/html2markdown@latest

$(GOPATH)/bin/go-readability:
	go install github.com/go-shiori/go-readability/cmd/go-readability@latest


