alias d='docker'
alias dc='docker-compose'
alias dcd='docker-compose down'
alias dce='docker-compose exec'
alias dcl='docker-compose logs'
alias dcr='docker-compose run'
alias dcu='docker-compose up -d --remove-orphans'
alias dcur='docker-compose up -d --force-recreate --remove-orphans'
alias de='docker exec -it'
alias di='docker images'
alias dl='docker logs'
alias dm='docker-machine'
alias dps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}"'
alias dpsa='docker ps -a'
alias dr='docker run'
alias drd='docker run -d --rm'
alias drit='docker run -it --rm'
alias driv='docker run -it --rm -v $(pwd):/data'
alias drm='docker rm'
alias drma='docker rm $(docker ps -a -q)'
alias drmi='docker rmi'
alias drmia='docker rmi $(docker images -q)'
alias dsp='docker system prune'
alias dst='docker stop'
alias dsta='docker stop $(docker ps -a -q)'

alias laws='docker run --network localstack --rm -it amazon/aws-cli --endpoint-url=http://localstack:4566'
