if [[ -x "$(command -v docker-compose)" ]]; then
  alias dc='docker-compose'
  alias dcd='docker-compose down'
  alias dce='docker-compose exec'
  alias dcl='docker-compose logs --tail 100'
  alias dcr='docker-compose run'
  alias dcu='docker-compose up -d --remove-orphans'
  alias dcur='docker-compose up -d --force-recreate --remove-orphans'
  alias dcurl='docker-compose up -d --force-recreate --remove-orphans && docker-compose logs --tail 100 -f'
fi
if [[ -x "$(command -v docker)" ]]; then
  alias d='docker'
  alias de='docker exec -it'
  alias di='docker images'
  alias dl='docker logs --tail 100'
  alias dm='docker-machine'
  alias dps='docker ps -a --format "table {{.ID}}\t{{.Image}}\t{{.Status}}"'
  alias dpsa='docker ps -a'
  alias dr='docker run'
  alias drd='docker run -d --rm'
  alias drit='docker run -it --rm'
  alias driv='docker run -it --rm -v $(pwd):/data'
  alias drm='docker rm'
  alias drma='docker rm $(docker ps -a -q)'
  alias drmse='docker rm $(docker ps -a -q -f status=exited)'
  alias drmi='docker rmi'
  alias drmia='docker rmi $(docker images -q)'
  alias dsp='docker system prune'
  alias dst='docker stop'
  alias dsta='docker stop $(docker ps -a -q)'
  alias dspa='docker system prune -a'
  alias laws='docker run --network localstack --rm -it amazon/aws-cli --endpoint-url=http://localstack:4566'
fi
