if [[ -x "$(command -v hindsight)" ]]; then
  alias h='hindsight'
  # memory
  alias hm='hindsight memory'
  alias hmrt='hindsight memory retain'
  alias hmrf='hindsight memory retain-files'
  alias hmrc='hindsight memory recall'
  alias hmrf='hindsight memory reflect'
  alias hmh='hindsight memory history'
  alias hmco='hindsight memory clear-observations'
  # bank
  alias hb='hindsight bank'
  alias hbl='hindsight bank list'
  alias hbd='hindsight bank disposition'
  alias hbsd='hindsight bank set-disposition'
  alias hbs='hindsight bank stats'
  alias hbn='hindsight bank name'
  alias hbm='hindsight bank mission'
  alias hbco='hindsight bank clear-observations'
  alias hbcr='hindsight bank consolidation-recover'
  # document
  alias hd='hindsight document'
  alias hdl='hindsight document list'
  alias hdg='hindsight document get'
  alias hdu='hindsight document update'
  alias hdd='hindsight document delete'
  # entity
  alias he='hindsight entity'
  alias hel='hindsight entity list'
  alias heg='hindsight entity get'
  # operation
  alias ho='hindsight operation'
  alias hol='hindsight operation list'
  alias hog='hindsight operation get'
  alias hoc='hindsight operation cancel'
  alias hor='hindsight operation retry'
  # webhook
  alias hw='hindsight webhook'
  alias hwl='hindsight webhook list'
  alias hwc='hindsight webhook create'
  alias hwu='hindsight webhook update'
  alias hwd='hindsight webhook deliveries'
  alias hwrm='hindsight webhook delete'
  # knowledge-base
  alias hkb='hindsight knowledge-base'
  alias hkbt='hindsight knowledge-base tree'
  alias hkbcf='hindsight knowledge-base create-folder'
  alias hkbcp='hindsight knowledge-base create-page'
  alias hkbgp='hindsight knowledge-base get-page'
  alias hkbs='hindsight knowledge-base search'
  alias hkbu='hindsight knowledge-base update'
  alias hkbe='hindsight knowledge-base export'
  alias hkbrm='hindsight knowledge-base delete'
  # audit
  alias ha='hindsight audit'
  alias hal='hindsight audit list'
  # misc
  alias hcfg='hindsight configure'
  alias hp='hindsight profile'
  alias hpl='hindsight profile list'
  alias hps='hindsight profile show'
  alias hpc='hindsight profile create'
  alias hpd='hindsight profile delete'
  alias hui='hindsight ui'
  alias hx='hindsight explore'
  alias hfsm='hindsight fs mount'
fi
